<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategoriasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('categorias')->insert([
            ["id"=>1,"nombre"=>"Despensa y Bebida","categoria_id"=>null],
                ["id"=>2,"nombre"=>"Aperitivos y Snacks","categoria_id"=>1],
                    ["id"=>3,"nombre"=>"Barritas","categoria_id"=>2],
                    ["id"=>4,"nombre"=>"Frutos Secos","categoria_id"=>2],
                    ["id"=>5,"nombre"=>"Tortitas","categoria_id"=>2],
                    ["id"=>6,"nombre"=>"Otros Snacks","categoria_id"=>2],
                ["id"=>7,"nombre"=>"Azúcares, Mieles y Edulcorantes","categoria_id"=>1],
                    ["id"=>8,"nombre"=>"Azúcar","categoria_id"=>7],
                    ["id"=>9,"nombre"=>"Chocolate","categoria_id"=>7],
                    ["id"=>10,"nombre"=>"Estevia y Otros Edulcorantes","categoria_id"=>7],
                    ["id"=>11,"nombre"=>"Melazas y Panela","categoria_id"=>7],
                    ["id"=>12,"nombre"=>"Miel, Jalea Real y Polen","categoria_id"=>7],
                    ["id"=>13,"nombre"=>"Siropes","categoria_id"=>7],
                ["id"=>14,"nombre"=>"Cereales y Semillas","categoria_id"=>1],
                    ["id"=>15,"nombre"=>"Cereales","categoria_id"=>14],
                    ["id"=>16,"nombre"=>"Semillas","categoria_id"=>14],
                ["id"=>17,"nombre"=>"Conservas","categoria_id"=>1],
                    ["id"=>18,"nombre"=>"Mermeladas y Compotas","categoria_id"=>17],
                    ["id"=>19,"nombre"=>"Patés","categoria_id"=>17],
                    ["id"=>20,"nombre"=>"Conservas de Pescado","categoria_id"=>17],
                    ["id"=>21,"nombre"=>"Conservas Vegetales","categoria_id"=>17],
                ["id"=>22,"nombre"=>"Derivados Vegetales y Sustitutivos","categoria_id"=>1],
                    ["id"=>23,"nombre"=>"Hamburguesas y Salchichas","categoria_id"=>22],
                    ["id"=>24,"nombre"=>"Platos Preparados","categoria_id"=>22],
                    ["id"=>25,"nombre"=>"Seitán, soja y tofu","categoria_id"=>22],
                    ["id"=>26,"nombre"=>"Postres Vegetales","categoria_id"=>22],
                ["id"=>27,"nombre"=>"Lácteos","categoria_id"=>1],
                ["id"=>28,"nombre"=>"Pasta, Arroces y Legumbres","categoria_id"=>1],
                    ["id"=>29,"nombre"=>"Arroces","categoria_id"=>28],
                    ["id"=>30,"nombre"=>"Legumbres","categoria_id"=>28],
                    ["id"=>31,"nombre"=>"Pasta","categoria_id"=>28],
                ["id"=>32,"nombre"=>"Repostería y Panadería","categoria_id"=>1],
                    ["id"=>33,"nombre"=>"Bollería y Galletas","categoria_id"=>32],
                    ["id"=>34,"nombre"=>"Harinas y Levaduras","categoria_id"=>32],
                    ["id"=>35,"nombre"=>"Pan","categoria_id"=>32],
                    ["id"=>36,"nombre"=>"Pizzas","categoria_id"=>32],
                    ["id"=>37,"nombre"=>"Repostería","categoria_id"=>32],
                ["id"=>38,"nombre"=>"Salsas y Condimentos","categoria_id"=>1],
                    ["id"=>39,"nombre"=>"Condimentos","categoria_id"=>38],
                    ["id"=>40,"nombre"=>"Salsas","categoria_id"=>38],
                ["id"=>41,"nombre"=>"Sopas, Caldos y Cremas","categoria_id"=>1],
                    ["id"=>42,"nombre"=>"Caldos","categoria_id"=>41],
                    ["id"=>43,"nombre"=>"Cremas y sopas","categoria_id"=>41],
                ["id"=>44,"nombre"=>"Vinagres y Aceites","categoria_id"=>1],
                    ["id"=>45,"nombre"=>"Aceite","categoria_id"=>44],
                    ["id"=>46,"nombre"=>"Vinagre","categoria_id"=>44],
                ["id"=>47,"nombre"=>"Bebidas y Refrescos","categoria_id"=>1],
                    ["id"=>48,"nombre"=>"Bebidas vegetales","categoria_id"=>47],
                    ["id"=>49,"nombre"=>"Refrescos","categoria_id"=>47],
                    ["id"=>50,"nombre"=>"Zumos","categoria_id"=>47],
                ["id"=>51,"nombre"=>"Café y Té","categoria_id"=>1],
                    ["id"=>52,"nombre"=>"Café","categoria_id"=>51],
                    ["id"=>53,"nombre"=>"Infusiones","categoria_id"=>51],
                    ["id"=>54,"nombre"=>"Té","categoria_id"=>51],
                ["id"=>101,"nombre"=>"Superalimentos","categoria_id"=>1],
                ["id"=>102,"nombre"=>"Complementos y bienestar","categoria_id"=>1],
            ["id"=>55,"nombre"=>"Mercado","categoria_id"=>null],
                ["id"=>56,"nombre"=>"Frutas","categoria_id"=>55],
                ["id"=>57,"nombre"=>"Verduras","categoria_id"=>55],
                ["id"=>58,"nombre"=>"Carnicería","categoria_id"=>55],
                ["id"=>59,"nombre"=>"Quesos","categoria_id"=>55],
                ["id"=>60,"nombre"=>"Platos preparados","categoria_id"=>55],
            ["id"=>61,"nombre"=>"Bebés y peques","categoria_id"=>null],
                ["id"=>62,"nombre"=>"Alimentación infantil","categoria_id"=>61],
                ["id"=>63,"nombre"=>"Cuidado e higiene","categoria_id"=>61],
            ["id"=>64,"nombre"=>"Belleza e higiene","categoria_id"=>null],
                ["id"=>65,"nombre"=>"Higiene","categoria_id"=>64],
                    ["id"=>66,"nombre"=>"Cuidado bucal","categoria_id"=>65],
                    ["id"=>67,"nombre"=>"Cuidado facial","categoria_id"=>65],
                    ["id"=>68,"nombre"=>"Cuidado corporal","categoria_id"=>65],
                    ["id"=>69,"nombre"=>"Cuidado del pelo","categoria_id"=>65],
                    ["id"=>70,"nombre"=>"Higiene íntima","categoria_id"=>65],
                    ["id"=>71,"nombre"=>"Sexualidad","categoria_id"=>65],
                ["id"=>72,"nombre"=>"Belleza","categoria_id"=>64],
                    ["id"=>73,"nombre"=>"Maquillaje","categoria_id"=>72],
                    ["id"=>74,"nombre"=>"Depilación","categoria_id"=>72],
                    ["id"=>75,"nombre"=>"Protección solar","categoria_id"=>72],
            ["id"=>76,"nombre"=>"Hogar","categoria_id"=>null],
                ["id"=>77,"nombre"=>"Accesorios","categoria_id"=>76],
                ["id"=>78,"nombre"=>"Limpieza","categoria_id"=>76],
                ["id"=>79,"nombre"=>"Cuidado de la ropa","categoria_id"=>76],
                ["id"=>80,"nombre"=>"Utensilios","categoria_id"=>76],
            ["id"=>81,"nombre"=>"Mascotas","categoria_id"=>null],
                ["id"=>82,"nombre"=>"Accesorios","categoria_id"=>81],
                ["id"=>83,"nombre"=>"Complementos y vitaminas","categoria_id"=>81],
                ["id"=>84,"nombre"=>"Comida y cuidado gatos","categoria_id"=>81],
                ["id"=>85,"nombre"=>"Comida y cuidado perros","categoria_id"=>81],
            ["id"=>86,"nombre"=>"Congelados","categoria_id"=>null],
                ["id"=>87,"nombre"=>"Dulce","categoria_id"=>86],
                ["id"=>88,"nombre"=>"Salado","categoria_id"=>86],
            ["id"=>89,"nombre"=>"Complementos y vitaminas","categoria_id"=>null],
                ["id"=>90,"nombre"=>"Antioxidantes","categoria_id"=>89],
                ["id"=>91,"nombre"=>"Pelo y piel","categoria_id"=>89],
                ["id"=>92,"nombre"=>"Articulaciones y circulación","categoria_id"=>89],
                ["id"=>93,"nombre"=>"Detox y tránsito","categoria_id"=>89],
                ["id"=>94,"nombre"=>"Equilibrio femenino","categoria_id"=>89],
                ["id"=>95,"nombre"=>"Equilibrio masculino","categoria_id"=>89],
                ["id"=>96,"nombre"=>"Maternidad y bebé","categoria_id"=>89],
                ["id"=>97,"nombre"=>"Mente y performance","categoria_id"=>89],
                ["id"=>98,"nombre"=>"Estrés y calidad del sueño","categoria_id"=>89],
                ["id"=>99,"nombre"=>"Visión","categoria_id"=>89],
                ["id"=>100,"nombre"=>"Vitalidad e inmunidad","categoria_id"=>89],
        ]
        );
    }
}
